# Generated by Django 5.2.1 on 2025-05-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='condition',
            field=models.BooleanField(default=False, verbose_name='Состояние новое?'),
        ),
    ]
